version: '3.8'

services:
    web:
      build: .
      ports:version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"  # Map container port 5000 to host
    volumes:
      - .:/app  # Mount the current directory inside the container
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

